const express = require('express');
app.use('/api/duo-vibes', duoVibesRoutes);
const express = require('express');
const app = express();

app.use(express.json());
const authRoutes = require('./routes/authRoutes');
const mpesaRoutes = require('./routes/mpesaRoutes');
const airtelRoutes = require('./routes/airtelRoutes');
const paypalRoutes = require('./routes/paypalRoutes');
const bankRoutes = require('./routes/bankRoutes');
const voicePostRoutes = require('./routes/voicePostRoutes');
const smartFeedRoutes = require('./routes/smartFeedRoutes');
const moodFeedRoutes = require('./routes/moodFeedRoutes');
const minigameRoutes = require('./routes/minigameRoutes');
const vibeChallengeRoutes = require('./routes/vibeChallengeRoutes');
const enhancedNotificationRoutes = require('./routes/enhancedNotificationRoutes');
app.use('/api/auth', authRoutes);
app.use('/api/mpesa', mpesaRoutes);
app.use('/api/airtel', airtelRoutes);
app.use('/api/paypal', paypalRoutes);
app.use('/api/bank', bankRoutes);
app.use('/api/voice-post', voicePostRoutes);
app.use('/api/smart-feed', smartFeedRoutes);
app.use('/api/mood-feed', moodFeedRoutes);
app.use('/api/minigame', minigameRoutes);
app.use('/api/vibe-challenges', vibeChallengeRoutes);
app.use('/api/enhanced-notifications', enhancedNotificationRoutes);
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
});
const autoTranslateRoutes = require('./routes/autoTranslateRoutes');
const blackChatRoutes = require('./routes/blackChatRoutes');
const duoVibesRoutes = require('./routes/duoVibesRoutes');
app.use('/api/auto-translate', autoTranslateRoutes);
app.use('/api/minigames', minigameRoutes);
app.use('/api/black-chat', blackChatRoutes);
app.use('/api/duo-vibes', duoVibesRoutes);
const textToSpeechRoutes = require('./routes/textToSpeechRoutes');
app.use('/api/text-to-speech', textToSpeechRoutes);
